-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('PAID', 'UNPAID', 'IN_PROGRESS') NOT NULL DEFAULT 'PAID',
    MODIFY `delivery_status` ENUM('DELIVERED', 'NOT_DELIVERED', 'IN_THE_WAY') NOT NULL DEFAULT 'DELIVERED';

-- AlterTable
ALTER TABLE `profiles` MODIFY `role` ENUM('USER', 'ADMIN', 'OWNER') NOT NULL DEFAULT 'USER';
