version: '3.8'
services:
  db:
    container_name: db
    ports:
      - '3306:3306'
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: maxaro
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
